# PyInstaller build spec for TweetDelete.
#
# Run from the project root (the folder containing this file) with:
#   pyinstaller build.spec
#
# Produces a one-folder build at dist/TweetDelete/ containing TweetDelete.exe
# plus its bundled files. One-folder (rather than --onefile) is deliberate:
# onefile self-extracts to a temp directory on every launch, which is both
# slower to start and more likely to trip antivirus heuristics that flag
# self-extracting executables. The Inno Setup installer (installer.iss)
# packages this whole folder behind a single Start Menu / desktop shortcut,
# so end users never see the individual files either way.

# -*- mode: python ; coding: utf-8 -*-

# Version resource: the single source of truth is VERSION in server.py, so
# the .exe's file properties can never drift from what the app reports in
# its footer. Two throwaway files are written at build time (EXE only
# accepts a filename for the version resource, and Inno Setup reads its
# version from a generated include - see packaging/installer.iss):
#   packaging/exe_version_info.py  - PyInstaller version-info source
#   packaging/build_version.iss   - #define MyAppVersion for installer.iss
# Both are regenerated on every build and ignored by git.
import re as _re

# Explicit rather than relying on Tree being injected into the spec
# namespace: keeps this spec valid under any PyInstaller 5/6 setup.
from PyInstaller.building.datastruct import Tree

with open("server.py", "r", encoding="utf-8") as _f:
    _VERSION = _re.search(r'^VERSION = "([^"]+)"', _f.read(), _re.M).group(1)
_ver = tuple(([int(p) for p in _VERSION.split(".")] + [0, 0, 0, 0])[:4])

with open("packaging/exe_version_info.py", "w", encoding="utf-8") as _f:
    _f.write(
        "# Generated by build.spec from server.py's VERSION - do not edit.\n"
        "VSVersionInfo(\n"
        "  ffi=FixedFileInfo(\n"
        "    filevers=%r, prodvers=%r, mask=0x3f, flags=0x0,\n"
        "    OS=0x40004, fileType=0x1, subtype=0x0, date=(0, 0)\n"
        "  ),\n"
        "  kids=[\n"
        "    StringFileInfo([\n"
        "      StringTable('040904B0', [\n"
        "        StringStruct('CompanyName', 'TweetDelete'),\n"
        "        StringStruct('FileDescription', 'TweetDelete - bulk delete your own X posts, reposts and likes'),\n"
        "        StringStruct('FileVersion', '%s'),\n"
        "        StringStruct('InternalName', 'TweetDelete'),\n"
        "        StringStruct('OriginalFilename', 'TweetDelete.exe'),\n"
        "        StringStruct('ProductName', 'TweetDelete'),\n"
        "        StringStruct('ProductVersion', '%s'),\n"
        "      ])\n"
        "    ]),\n"
        "    VarFileInfo([VarStruct('Translation', [1033, 1200])])\n"
        "  ]\n"
        ")\n" % (_ver, _ver, _VERSION, _VERSION)
    )

with open("packaging/build_version.iss", "w", encoding="utf-8") as _f:
    _f.write(
        "; Generated by build.spec from server.py's VERSION - do not edit.\n"
        "#define MyAppVersion \"%s\"\n" % _VERSION
    )

a = Analysis(
    ['tray_app.py'],
    pathex=[],
    binaries=[],
    datas=[
        # public/ minus the other platforms' help guides - the shared
        # source tree carries all of them, and this build ships only its
        # own (the same filter build_deb.sh applies to the Debian package).
        Tree('public', prefix='public', excludes=[
            'TweetDelete for Debian.pdf',
            'TweetDelete for Linux.pdf',
            'TweetDelete for Ubuntu.pdf',
        ]),
        ('packaging/icon.ico', '.'),
    ],
    hiddenimports=[
        # pystray picks its backend dynamically per-OS at import time, which
        # PyInstaller's static analysis can miss - list the Windows one
        # explicitly so it's always bundled regardless of what OS this spec
        # happens to be processed on.
        'pystray._win32',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='TweetDelete',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,  # no terminal window - this is the tray app, not a CLI tool
    icon='packaging/icon.ico',
    version='packaging/exe_version_info.py',
    disable_windowed_traceback=False,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='TweetDelete',
)
